name: SoulJars
version: ${version}
authors: [TheBusyBiscuit, kaiquebaccas]
website: https://github.com/kaiquebaccas/SoulJars-Slimefun5

api-version: '26.1'
main: io.github.thebusybiscuit.souljars.SoulJars

depend:
- Slimefun
